import { StyleSheet } from "react-native";

export const StyleInEvent = StyleSheet.create({
    Body:{
        backgroundColor:'white'
    },
    MainContainer:{
        flex:1,
        alignItems:'center',
        justifyContent:'space-around',
        padding:10,
    },
    Section1:{
        justifyContent:'center',
        alignItems:'center'
    },
    TextNombreEvent:{
        fontSize:26,
        color:'',
        textAlign:'center',
        fontWeight:'600'
    },
    TextParticipantesEvent:{
        fontWeight:'500',
        fontSize:18,
        color:'gray'
    },
    Section2:{
        width:'100%',gap:10
    },
    BtnRegistrarEntrada:{
        width:'100%',
        paddingHorizontal:30,
        paddingVertical:15,
        alignItems:'center',
        borderRadius:10,
        backgroundColor:'#023e8a'
    },
    TextBtnResgistrarEntrada:{
        fontSize:18,
        fontWeight:'600',
        color:'white'
    },
    BtnNuevoParticipante:{
        width:'100%',
        paddingHorizontal:30,
        paddingVertical:15,
        alignItems:'center',
        borderRadius:10,
        backgroundColor:'#008000'
    },
    TextBtnNuevoParticipante:{
        fontSize:18,
        fontWeight:'600',
        color:'white'
    },


})