import { StyleSheet } from "react-native";

export const StyleParticipantes = StyleSheet.create({
    Body:{
        backgroundColor:'white',
    },
    MainContainer:{
        paddingHorizontal:5,
    },
    SearchContainer:{
        borderWidth:1,
        borderRadius:10,
        height:50,
        flexDirection:'row',
        borderColor:'#ced4da',
        width:`100%`,
    },
    BtnSearch:{
        padding:5,
        justifyContent:'center',
        alignItems:'center'
    },
    IconBtnSearch:{
        height:'90%',
        width:40,
        objectFit:'contain',
    },
    TextInputSearch:{
        fontSize:16,
        width:`85%`,
        borderTopRightRadius:10,
        borderBottomRightRadius:10,
        display: `flex`,
    },
    ContainerFilter:{
        alignItems:'flex-start',
        justifyContent:'flex-start',
        paddingVertical:5,
        gap:2,
    },
    BtnDeployFilter:{
        borderWidth:1,
        borderColor:'#ced4da',
        paddingHorizontal:10,
        paddingVertical:5,
        borderRadius:10,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between'
    },
    SelectContainerFilter:{
        borderWidth:1,
        paddingHorizontal:5,
        paddingVertical:5,
        borderRadius:10,
        width:'52%',
        gap:5,
        position:'absolute',
        marginTop:50,
        zIndex:20,
        backgroundColor:'white'
    },
    SelectContainerFilterHidden:{
        display:'none'
    },
    SelectBtnForFilter:{
        width:'100%',
        padding:5,
        borderRadius:5,
    },
    IconArrow:{
        height:30,
        width:30
    }
});