import { StyleSheet } from "react-native";

export const StyleCardhome = StyleSheet.create({
  BackImage: {
    height: 150,
    width: "100%",
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  ContainerLocation: {
    gap: 5,
    flexDirection: "row",
    borderRadius: 10,
    alignItems: "center",
  },
  IconLocation: {
    height: 10,
    width: 10,
    objectFit: "contain",
    tintColor: "#0087FF",
  },
  TextLocation: {
    color: "#003876",
    fontWeight: "400",
    fontSize: 12,
  },
  ContainerDia_Hora: {
    justifyContent: "space-between",
    flexDirection: "row",
    width: "100%",
  },
  ContainerDia: {
    flexDirection: "row",
    gap: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  SubContainerDia: {
    gap: 5,
    flexDirection: "row",
    borderRadius: 15,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#0087FF",
    paddingHorizontal: 10,
    borderRadius: 5,
    paddingVertical: 5,
  },
  IconDia: {
    height: 15,
    width: 15,
    objectFit: "contain",
    tintColor: "#0087FF",
  },
  TextDia: {
    color: "#003876",
    fontWeight: "400",
    fontSize: 15,
  },
  GuionDia_Hora: {
    fontSize: 20,
    color: "#00377687",
  },
  ContainerHora: {
    gap: 5,
    flexDirection: "row",
    borderRadius: 10,
    alignItems: "center",
  },
  IconHora: {
    height: 16,
    width: 16,
    objectFit: "contain",
    tintColor: "#0087FF",
  },
  TextHora: {
    color: "#003876",
    fontWeight: "400",
    fontSize: 16,
  },
  CardEvent: {
    marginBottom: 10,
    borderRadius: 10,
    gap: 10,
    position: "relative",
    borderWidth: 1,
    borderColor: "#0037763c",
    boxShadow: "0px 0px 5px 1px #E4E5E7 ",
  },
  BtnInCardEvent: {
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 20,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#0087FF",
  },
  CardEventbody: {
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "white",
    width: "100%",
    padding: 10,
    flexDirection: "row",
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    gap: 10,
  },
});
